// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RPAS.Governance.Persistence.Data;

#nullable disable

namespace RPAS.Governance.Persistence.Migrations
{
    [DbContext(typeof(GovernanceDbContext))]
    partial class GovernanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RPAS.Governance.Core.Models.Governance.AuthorityToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedPaths")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RitualType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("authority_tokens", (string)null);
                });

            modelBuilder.Entity("RPAS.Governance.Core.Models.Governance.GovernanceLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessCaseJson")
                        .HasColumnType("text");

                    b.Property<string>("GovernorNotes")
                        .HasColumnType("text");

                    b.Property<string>("IdeationJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("InitiatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsOverridden")
                        .HasColumnType("boolean");

                    b.Property<string>("OverrideJustification")
                        .HasColumnType("text");

                    b.Property<string>("RitualType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("governance_ledger", null, t =>
                        {
                            t.HasCheckConstraint("CK_Ledger_Override", "(\"IsOverridden\" = false) OR (\"IsOverridden\" = true AND \"OverrideJustification\" IS NOT NULL AND \"OverrideJustification\" != '')");
                        });
                });

            modelBuilder.Entity("RPAS.Governance.Core.Models.Rituals.BusinessCase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasJsonPropertyName("id");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("approval_status");

                    b.Property<string>("CoreRequirements")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasJsonPropertyName("core_requirements");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("created_at");

                    b.Property<string>("EstimatedCosts")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasJsonPropertyName("estimated_costs");

                    b.Property<string>("ExecutiveSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("executive_summary");

                    b.Property<string>("ExpectedBenefits")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasJsonPropertyName("expected_benefits");

                    b.Property<string>("IdeationSummaryId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("ideation_summary_id");

                    b.Property<string>("KeyRisks")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasJsonPropertyName("key_risks");

                    b.Property<string>("Placeholders")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasJsonPropertyName("placeholders");

                    b.Property<string>("ProblemStatement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("problem_statement");

                    b.Property<string>("ProposedSolution")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("proposed_solution");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("recommendation");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasJsonPropertyName("version");

                    b.HasKey("Id");

                    b.ToTable("BusinessCases", null, t =>
                        {
                            t.HasCheckConstraint("CK_BusinessCase_Status", "\"ApprovalStatus\" IN ('PENDING', 'APPROVED', 'REJECTED')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
